-- Software Engineer: 2 - The Perfect Arrangement

/*
Enter your query here.
*/
SELECT ID, FIRST_NAME, LAST_NAME
FROM CUSTOMER
WHERE CHAR_LENGTH(CONCAT(FIRST_NAME, LAST_NAME)) < 12
ORDER BY CHAR_LENGTH(CONCAT(FIRST_NAME, LAST_NAME)) ASC,
         LOWER(CONCAT(FIRST_NAME, LAST_NAME)) ASC,
         ID ASC;
